Models
CastelShal/Rest-API pull request #5
Opened 2024-02-07 17:18 UTC by AdleenaLobo

Done with delet events, create new feilds for collaborater1 and 2 , new feild for ecc points, made controllers to browse by department , browse by name and to get all the events.(Please check if the code is correct )

2024-02-07 19:37 UTC, CastelShal commented on controllers/eventController.js
> +    const event = await Event.findAll({
findOne

2024-02-07 19:40 UTC, CastelShal commented on controllers/eventController.js
> +              [Sequelize.Op.iLike]: req.params.department,
Sequelize docs say iLike is Postgres specific

2024-02-07 19:44 UTC, CastelShal commented on controllers/organiserController.js
> +}
Accept and check the password as well and we can make this the login function for organizers

2024-02-07 19:47 UTC, CastelShal commented on routes/events.js
> +router.get(":/events", getAllEvents);
Put the colons after the route names, and make them :id so they actually get parsed

2024-02-07 19:51 UTC, CastelShal commented on routes/events.js
> +router.post("/", deleteEvent);
probably use the 'delete' method here instead of post

2024-02-07 19:53 UTC, CastelShal commented on controllers/eventController.js
> +        eventName: req.params.eventName,
POST method will contain the eventName as a property in res.body instead of req.params.

2024-02-07 19:55 UTC, CastelShal commented on routes/organizer.js
> +router.get(":/email", getOrganizer); // /:id is a parameter that will be filled in by the Express framework
same as above

2024-02-09 02:26 UTC, AdleenaLobo commented
Made repective changes

2024-02-09 18:17 UTC, CastelShal requested changes

2024-02-09 18:17 UTC, CastelShal commented on config.js
> +  password: "AdleenaLobo2024SE", // this is not the password, actually put your password
Ya did it again •√•

2024-02-09 18:17 UTC, CastelShal commented on controllers/eventController.js
> +              [Sequelize.Op.regexp]: req.params.department,
req.params.department is not a regex. It will not case insensitive match.

Try: https://stackoverflow.com/questions/41728023/sequelize-case-insensitive-like#answer-41732931

2024-02-09 18:17 UTC, CastelShal commented on routes/events.js
> +router.get("/:name_event", getEventByName);
change to "/:eventName"

2024-02-09 18:17 UTC, CastelShal commented on routes/events.js
> +router.get("/:department_event", getEventByDepartment);
change to "/:department"

2024-02-09 18:42 UTC, CastelShal commented on controllers/eventController.js
> +    const event = await Event.findOneAndDelete({
I cannot seem to find this sequelize function anywhere in the docs

2024-02-09 18:43 UTC, CastelShal commented on routes/events.js
> +router.delete("/", deleteEvent);
The controller tries to find a eventName. Append :eventName to the end of the route

2024-02-09 19:31 UTC, CastelShal commented on models/event.js
>    },
To-Do: Add a string called url to hold the url of the uploaded image for the event.

(I'm just pushing everything on you ATP :D )

2024-02-12 16:02 UTC, AdleenaLobo commented
Added the event controllers

2024-02-12 16:26 UTC, CastelShal commented on controllers/eventController.js
> +  const lowercaseEventName = eventName.toLowerCase();
I don't think this is a good idea. We'll fix this later

2024-02-12 16:26 UTC, CastelShal approved these changes

2024-02-12 16:28 UTC, merged