Models
CastelShal/Rest-API pull request #8
Opened 2024-02-13 15:10 UTC by AdleenaLobo

Did changes to the search event by name to be case insenstive

2024-02-15 15:34 UTC, CastelShal requested changes
Just add the one line and add the .js back
(⁠◠⁠‿⁠◕⁠)

2024-02-15 15:34 UTC, CastelShal commented on controllers/eventController.js
> +import Event from "../models/event.
Uhhhhh, why remove the .js?

2024-02-15 15:34 UTC, CastelShal commented on controllers/eventController.js
> +            req.params.eventName.toLowerCase()
Just a minor change, as shown in the code here

https://stackoverflow.com/questions/41728023/sequelize-case-insensitive-like#answer-41732931

2024-02-16 16:38 UTC, AdleenaLobo commented
made changes shalome

2024-02-17 17:51 UTC, CastelShal commented
> made changes shalome
> 

Huhhhhhhhh

2024-02-18 09:28 UTC, CastelShal approved these changes

2024-02-18 09:29 UTC, CastelShal approved these changes

2024-02-18 09:30 UTC, merged